#!/bin/bash

while [ 1 -eq 1 ]
do
java -cp ../caos/ RandomInstance test.wcsp $1 $2 $RANDOM
opt=`../aolib/aolib -f test.wcsp 2> /dev/null | grep Solution | egrep -o "[0-9]+\.?[0-9]*"` 
if [ ! -z "$opt" ]
then
        fabe=`./fabe -f test.wcsp 2> /dev/null | grep Solution | egrep -o "[0-9]+\.?[0-9]*"`
        echo $opt $fabe
        if [ -z "$fabe" ]
        then
                exit 0
        elif [ `python -c "print($opt == $fabe)"` != "True" ]
        then
                exit 0
        fi
fi
done
