#!/bin/bash

while [ 1 -eq 1 ]
do
java -cp ../caos/ RandomInstance test.wcsp $1 $2 $RANDOM
opt=`../aolib/aolib -f test.wcsp | grep Solution`
opt=${opt##* }
opt=${opt%.*}
fabe=`./fabe -f test.wcsp | tail -n 1`
if [ $opt != $fabe ]
then
        exit 0
fi
done
