#!/bin/bash

out_dir="./random"
bin="./fabe"
n=2

mkdir -p ${out_dir}
rm -rf ${out_dir}/*

for wcsp in $*
do
        for i in `seq 1 $n`
        do
                log=${out_dir}/${wcsp##*/}.$RANDOM.log
                ${bin} -f $wcsp > ${log}
        done
done
