#!/bin/bash

red=$(tput setaf 1)
green=$(tput setaf 2)
bold=$(tput bold)
underline=$(tput smul)
normal=$(tput sgr0)
float_regex="[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?"

fabe="/home/filippo/iiia/fabe/fabe"
aolib="/home/filippo/iiia/aolib/aolib"
tmp="."

# default values
out=/dev/null
mbe="fabe"
order="fabe"
alg="rbfaoo"
seed=0
ib=2

usage() {
        echo -n "Usage: $0 [-v] [-s seed] [-m <${underline}fabe${normal}|aolib>] [-i ibound] "
        echo "[-o <${underline}fabe${normal}|aolib>] [-a <${underline}rbfaoo${normal}|aobb|aobf>] -f instance" 1>&2
        exit 1
}

while getopts ":f:m:i:s:a:o:v" opt; do
    case "${opt}" in
        f)
            instance=${OPTARG}
            [ -f "$instance" ] || usage
            ;;
        m)
            mbe=${OPTARG}
            [[ $mbe == "fabe" || $mbe == "aolib" ]] || usage
            ;;
        i)
            ib=${OPTARG}
            ;;
        o)
            order=${OPTARG}
            [[ $order == "fabe" || $order == "aolib" ]] || usage
            ;;
        a)
            alg=${OPTARG}
            ((alg == "rbfaoo" || alg == "aobb" || alg == "aobf")) || usage
            ;;
        v)
            out=/dev/stdout
            ;;
        s)
            seed=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${instance}" ]
then
        usage
fi

ord="$(mktemp)"
pt="$(mktemp)"
bin="$(mktemp)"
log="$(mktemp)"

if [ $order == "fabe" ]
then
        # Ordering
        $fabe -f $instance -O $ord | tee -a $log > $out
        t_ord=`grep "Order computation runtime" $log | egrep -o $float_regex`

        if [ $mbe == "fabe" ]
        then
                # Pseudotree
                $aolib -f $instance -P $pt -E $ord | tee -a $log > $out
                # MBE
                $fabe -f $instance -o $pt -m $bin -i $ib | tee -a $log > $out
                [ -s $bin ] || exit 1
                red=`grep "Value redundancy" $log | egrep -o "\([0-9]*\.?[0-9]+\)" | egrep -o "[0-9]*\.?[0-9]+"`
                t_mbe=`grep "Bucket elimination runtime" $log | egrep -o $float_regex`
                t_io=`grep "I/O" $log | egrep -o $float_regex`
                # Search
                $aolib -a $alg -f $instance -i $ib --mbe-import $bin -E $ord | tee -a $log > $out
        else
                # Pseudotree + MBE + Search
                $aolib -a $alg -f $instance -E $ord -i $ib | tee -a $log > $out
                red="-"
                t_mbe=`grep "Mini bucket finished in" $log | egrep -o $float_regex`
                t_io=0
        fi
else
        if [ $mbe == "fabe" ]
        then
                # Ordering + Pseudotree
                $aolib -f $instance -P $pt -s $seed | tee -a $log > $out
                t_ord=`grep "Ordering generation phase" $log | egrep -o $float_regex`
                # MBE
                $fabe -f $instance -o $pt -m $bin -i $ib | tee -a $log > $out
                [ -s $bin ] || exit 1
                red=`grep "Value redundancy" $log | egrep -o "\([0-9]*\.?[0-9]+\)" | egrep -o "[0-9]*\.?[0-9]+"`
                t_mbe=`grep "Bucket elimination runtime" $log | egrep -o $float_regex`
                t_io=`grep "I/O" $log | egrep -o $float_regex`
                # Search
                $aolib -a $alg -f $instance -i $ib --mbe-import $bin -s $seed | tee -a $log > $out
        else
                # Ordering + Pseudotree + MBE + Search
                $aolib -a $alg -f $instance -s $seed -i $ib | tee -a $log > $out
                red="-"
                t_ord=`grep "Ordering generation phase" $log | egrep -o $float_regex`
                t_mbe=`grep "Mini bucket finished in" $log | egrep -o $float_regex`
                t_io=0
        fi
fi

t_sea=`grep "Solving:" $log | egrep -o $float_regex`
sol=`grep "Solution:" $log | egrep -o $float_regex`

rm $pt $bin $ord $log

echo "+--------------------------------------+--------------------------------------+"
echo -n "| Value redundancy                     |"
if [ $red == "-" ]
then
        printf "% 37s |\n" "-"
else
        printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$red"`
fi
echo -n "| Solution value                       |"
printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$sol"`
echo "+--------------------------------------+--------------------------------------+"
echo -n "| Ordering computation runtime         |"
printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$t_ord"`
echo -n "| Mini-bucket elimination runtime      |"
printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$t_mbe"`
echo -n "| Search runtime                       |"
printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$t_sea"`
echo "+--------------------------------------+--------------------------------------+"
t_tot=`python -c "print($t_ord + $t_mbe + $t_sea)"`
echo -n "| Total runtime                        |"
printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$t_tot"`
echo -n "| I/O runtime                          |"
printf "% 37s |\n" `LC_NUMERIC="en_US.UTF-8" printf "%.8f" "$t_io"`
echo "+--------------------------------------+--------------------------------------+"

